### PR TITLE
Added Exashare support

### PR DESCRIPTION
**Pull request by Watilin**
Tested with a couple videos on Firefox and G-Chrome.

The name of the function to override was always the same but there are hints that it may change regulary, so I made it so the script can resist this kind of change.

### CODE REVIEW

**Comment by reek** [comment]
Thanks

**Comment by reek** [comment]
Dont work i have error
TypeError: /\bfunction ([\w_]+)\s*\(\s*\)\s*\{/.exec(...) is null

**Comment by Watilin** [comment]
I'll check that. On what browser and with what URL did it happen?

**Comment by reek** [comment]
Firefox + ABP + Greasemonkey

**Pull request merged**
