### PR TITLE
Fix FuckAdBlock.

### PR DESCRIPTION
**Pull request by angelsl**
Test: http://sitexw.fr/fuckadblock/.

I also changed `addScript`, because regex is unnecessary here (could lead to issues, if e.g. the added code has functions inside the function).

### CODE REVIEW

**Comment by Watilin** [comment]
I agree with the `addScript` modification, I just ran into the mentioned issue.

**Comment by reek** [comment]
Ok, I'll make all these changes, thank you

**Comment by reek** [comment]
Hi,

With Chrome + uBlock dont work on https://www.monova.org/search?term=game+of+thrones

**Comment by reek** [comment]
Hi,

I found a solution, but I will also keep yours because it will be useful when the class FuckAbBlock exist.

**Pull request closed without merging**
