### PR TITLE
Added antiblock rule for qnimate

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by reek** [comment]
Hi,

Thanks, but I can't accept as valid only for uBlock,

**Comment by KOLANICH** [comment]
>Thanks, but I can't accept as valid only for uBlock,
Would it break the list if it was opened in another blocker?
If it wouldn't, why not to include?
If will, why not to create a separate list for ublock?

**Comment by reek** [comment]
I want a solution that works with all adblockers.

**Comment by reek** [comment]
I just tested your rule Chrome and uBlock and it does not work

**Comment by KOLANICH** [comment]
In ff it works.
[In chrome and other browsers it doesn't.](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering)

**Comment by KOLANICH** [comment]
And yes, it will break the list for chrome versions of abp

**Pull request closed without merging**
