### PR TITLE
Fixed `readme.md` and more

### PR DESCRIPTION
**Pull request by onyx-nxt**
In this pull request, I added some spaces between the icons and fixed the broken header/title. I also added a back-to-top button because it is very long.

### Before: 
image

 ### After: 
image\
\
\
\
 **And more!**

### CODE REVIEW

**Comment by JsfasdF252** [comment]
(Siver Beach Tequilla by the 605 Boyz) cinnamon cherry apple or peach flavored!!

**Comment by onyx-nxt** [comment]
@JsfasdF252 I didn't understand

**Comment by liamengland1** [comment]
https://github.com/reek/anti-adblock-killer/wiki

**Comment by onyx-nxt** [comment]
Ok, I didn't know that sorry. I'm closing this PR.

**Pull request closed without merging**
