### PR TITLE
Remove broken filter

### PR DESCRIPTION
**Pull request by sammcj**
Remove invalid filter which is breaking the list from working with ublock origin.

SCR-20230427-mzgd
SCR-20230427-mynl

### CODE REVIEW

**Comment by krystian3w** [comment]
Nobody alive have power to merge also you should see "0 used out of 0" (list is marked as bad).

**Comment by sammcj** [comment]
I'm sorry @krystian3w I'm not sure I quite understand what you're asking.

The list was indeed marked as bad - but that means that the anti-adblock-killer doesn't work.

**Comment by kiloPause** [comment]
any fix?

**Comment by sammcj** [comment]
Yes, this is the PR to fix it.

**Comment by krystian3w** [comment]
But no one use custom link like:

`https://raw.githubusercontent.com/reek/anti-adblock-killer/fcaae226816e9d213f10d70ebf3dc97288b36920/anti-adblock-killer-filters.txt`

**Comment by sammcj** [comment]
Sorry I don't understand you @krystian3w

**Comment by ghost** [comment]
The list is blocked by uBlock Origin

**Pull request closed without merging**
