### PR TITLE
Update for Exashare

### PR DESCRIPTION
**Pull request by Watilin**
Exashare guys are swift, they adapted their code and made their anti-adblock function anonymous. So my new idea is to simply block their timeout, and I'm doing that by clearing *all* timers. Unfortunately, this breaks the jwplayer and it needs to be rearmed, so maybe there's a more elegant approach.

Tested with Firefox/Greasemonkey and Chrome/Tampermonkey, all versions up to date, all on Windows 7. My test pages were http://www.exashare.com/mq05imh2tor3 and http://www.exashare.com/embed-mq05imh2tor3-900x500.html.

### CODE REVIEW

**Comment by reek** [comment]
Hi,

I had thought to replace the player like this, suddenly no need to hack the timeout

<pre>
    exashare_com : {
      // issue: 
      host : ['exashare.com'],
      onIdle : function () {
        var op = document.querySelector('form input[name="op"]');
        if (op) { // skip countdown
          setTimeout(function () {
            op.parentNode.submit();
          }, 1e4);
        }
		var vplayer = document.querySelector('#vplayer');
        if (vplayer) { // 
		  // file: "http://fs27.exashare.com:8777/5sxkiakl3qm56odwt3nolgpwvpk3etu2c7yzyjco46u5dk7bljzrtrpvi2xq/v.mp4",
          var videoURL = document.body.innerHTML.match(/file: "(http:\/\/fs[0-9a-z]+.exashare.com:[0-9a-z]+\/[0-9a-z]+\/v.mp4)",/)[1];
          console.log(videoURL)
          Aak.player.html5(vplayer, {
            autostart : true,
            file : videoURL
          });
		  Aak.removeElement('#player_img');
        }
      }
    },
</pre>

**Comment by Watilin** [comment]
Actually I already tried to use your included player, but found it not to be flexible enough. It always imposes Flash whereas Exashare videos may be of HTML5 format. I think it's better to stick with the provided player whenever possible.

Besides, pay attention to `document.body.innerHTML`: it causes a serialization of the entire body's DOM. This can seriously slow down the page. See how I use `document.scripts` in my code to avoid that.

**Comment by Watilin** [comment]
#486 and #506 (should have done it in the first place)

**Comment by reek** [comment]
OK, in this case I am going to add your solution, thanks

**Comment by reek** [comment]
This solution use jwplayer6 same on exashare and have not to skip ads

<pre>
    exashare_com : {
      // by: Watilin
      // pull: https://github.com/reek/anti-adblock-killer/pull/519
      // issue: https://github.com/reek/anti-adblock-killer/issues/486
      // issue: https://github.com/reek/anti-adblock-killer/issues/506
      host : ['exashare.com'],
      onEnd : function () {

        // skip countdown
        var op = document.querySelector('form input[name="op"]');
        if (op) {
          setTimeout(function () {
            op.parentNode.submit();
          }, 1e4);
        }
		
        var vplayer = document.querySelector('#vplayer');
        if (vplayer) {
          var setupScript = Array.prototype.filter.call(
              document.scripts,
              function ($script) {
              var source = $script.innerHTML;
              return source && Aak.contains(source, "setup");
            })[0];
          // file: "http://fs27.exashare.com:8777/5sxkiakl3qm56odwt3nolgpwvpk3etu2c7yzyjco46u5dk7bljzrtrpvi2xq/v.mp4",
          var videoURL = setupScript.innerHTML.match(/file: "(http:\/\/fs[0-9a-z]+.exashare.com:[0-9a-z]+\/[0-9a-z]+\/v.mp4)",/)[1];
          console.log(videoURL)
          Aak.player.jwplayer6(vplayer, {
            autostart : true,
            file : videoURL
          });
          Aak.removeElement('#player_img');
        }
      }
    },
</pre>

**Comment by Watilin** [comment]
Ok but your `jwplayer6` has the same problem: it imposes Flash. Here's what I propose: making the player format an option. JW6's documentation ([here](http://support.jwplayer.com/customer/portal/articles/1413113-configuration-options-reference)) states that html5 is the default, we may stick to that for consistency.

`Aak.removeElement('#player_img');` is redundant with my update to the filter list.

About skipping the countdown: I have no problem with that, but isn't it a bit out of the scope of your script? It may be good to have it written somewhere what the script should do and what it shouldn't do.

I'm preparing a commit.

**Comment by Watilin** [comment]
With the code you proposed I'm getting the disable adblock message . Apparently the 15 s timer sees no difference between the original and replaced player.

Since in any way we're going to replace/rearm the player, I propose we kill that damn timer. I'll keep your idea of simply retrieving the video URL to shorten my code. Commit in 20 minutes :)

**Comment by reek** [comment]
Hi,

You have convinced me, I'll post your solution. (without skipper of course, I had added just to prevent me from doing so)

I greatly appreciate your help and I hope you continue to contribute to AAK

final version: https://gist.github.com/reek/dc234ea9687056bd99fe

PS: I also modified the function <code>addScript</code> and added function <code>addExternalScript</code>

Regards
Reek

**Comment by Watilin** [comment]
Well, I didn't see your reply. My commit is ready. I revert it if you prefer the previous version, unless you are going to update from your gist.
It's my pleasure to contribute to your project, and I'll gladly continue to do so ;)

**Comment by reek** [comment]
I'll post on my side, version gist serves me just to do user testing before posting.

Know that your help is always welcome.

See you
Reek

**Comment by Watilin** [comment]
Closing the PR.

I have to ask, are you ok with branching and PR stuff? Because, working from gists is not what GitHub was designed for. I'm no Git guru but I think I could be of some advice – if you ask for it ;)

**Comment by reek** [comment]
Hi,

Yes, you can close PR.

I do not activate the pull request because I want to have the same version on all platforms where AakScript is hosted, which poses problem is it does not have all the functionality to synchronize to GH.

Like I've said using the gist allowed me to test a beta version which I was not sure it works. By cons I could create a dev version of Aakscript in the repo GH.

Regards
Reek

**Comment by Watilin** [comment]
Wow, I juste performed a successful rebasing! Look at the network graph and see how it looks tidy and wonderful :P I'll keep on working on my own *exashare* branch as I suspect the guys are updating their site according to your updates. The price of fame ;)

Speaking about that, look at the *Graphs* section in your project's page, you'll see some nifty data about your fellow contributors. Notice how only merged pull requests count as an effective contribution. It would make more beautiful curves if you'd want to merge more often :D

Github provides a handy tool called deployment hooks. It allows you to run automated tasks when a certain event occurs, for example when something is pushed to your *master* branch.

Even without hooks, I suggest you make GitHub your base for deployment. Create a branch for each new version of your script, then push commits to this branch, then only merge into *master* when the version is complete. It's common practice. Branches are really easy! I promise you, once you'll get used to it, you'll never want to get back to working with gists ;)

**Comment by reek** [comment]
HI,

It's probably the case, thank you to take care of exashare, on my side I
will try to make the best use of GH features.

Regards
Reek

2015-08-08 5:52 GMT+02:00 Matilin Torre <notifications@github.com>:

**Pull request closed without merging**
