### PR TITLE
add bild.de

### PR DESCRIPTION
**Pull request by barthramsay**
fixes https://github.com/reek/anti-adblock-killer/issues/664

by the way: Sorry for the end of line change at the end. It should not change anything! I can only commit via browser here.

### CODE REVIEW

**Comment by reek** [comment]
HI,

Thanks, but dont work for me :(

**Comment by barthramsay** [comment]
Just retested with Chrome and uBlock and only the Easylist active.
It works here... did you checked the right raw file? Seems when I click on github on "raw" button it gives me the master branch but I created a `bild.de` branch.

Check with this fiter file:
```
https://raw.githubusercontent.com/barthramsay/anti-adblock-killer/bild.de/anti-adblock-killer-filters.txt
```

**Comment by barthramsay** [comment]
@reek can you please recheck? This website is the in the top 2 of German websites overall... it will help a lot of people in Germany. Thanks.

**Comment by barthramsay** [comment]
ok this is outdated, starting today :(

**Pull request closed without merging**
