### PR TITLE
block 'aabl' (anti adblock) element

### PR DESCRIPTION
**Pull request by Yannik**
fixes e.g. radiohamburg.de

### CODE REVIEW

**Comment by mapx-** [comment]
filters to fix the issue
```
@@||radiohamburg.de^$generichide
@@.png#$domain=radiohamburg.de
```

**Comment by Yannik** [comment]
@mapx- 
If I understand this correctly, this disables all filters except for the one on line 2 which hides all png's on the site, assuming all non-ad images are not in png format?

**Comment by mapx-** [comment]
The first 1 disables only the generic hiding filters
for example disable ###adsense, but cannot disable example.com###adsense

The second filter whitelists all the images (elements) containing `.png#`

**Comment by Yannik** [comment]
@mapx- 
>The first 1 disables only the generic hiding filters
for example disable ###adsense, but cannot disable example.com###adsense
Yes. My statement that this disables all rules was under the assumption that there were no distinct rules for the domain radiohamburg.de

>The second filter whitelists all the images (elements) containing .png#
What is that for?

Which rule is ultimately blocking the ads as well as the anti-adblock container?

**Comment by mapx-** [comment]
the ads are blocking by other (easylist) filters:
```
||partner.googleadservices.com^$third-party
||mookie1.com^$third-party
```

those above are only to bypass the site's anti adblocking trick 
(the same filters are already in easylist / aak for a lot of other sites)

**Comment by Yannik** [comment]
@mapx- 
Got it!
Shall I amend my PR to the 2 filters you proposed?

**Comment by mapx-** [comment]
well, your filter is ok too
`radiohamburg.de###aabl`

**Comment by mapx-** [comment]
let's see what will decide Reek

**Comment by mapx-** [comment]
so, my filters are whitelisting some elements used by the site (using inline scripting) to test if an adblocker is used.

your filter is hiding directly the overlay that site put above the normal page when is detecting the adblocker

**Comment by Yannik** [comment]
couldn't verify that they still use aabl, therefore closing this PR

**Pull request closed without merging**
